// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/notification-discord/pkg"
	"github.com/bborbe/notification/discord"
)

type ChannelCreator struct {
	CreateChannelStub        func(context.Context, discord.ChannelName) (*pkg.Channel, error)
	createChannelMutex       sync.RWMutex
	createChannelArgsForCall []struct {
		arg1 context.Context
		arg2 discord.ChannelName
	}
	createChannelReturns struct {
		result1 *pkg.Channel
		result2 error
	}
	createChannelReturnsOnCall map[int]struct {
		result1 *pkg.Channel
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ChannelCreator) CreateChannel(arg1 context.Context, arg2 discord.ChannelName) (*pkg.Channel, error) {
	fake.createChannelMutex.Lock()
	ret, specificReturn := fake.createChannelReturnsOnCall[len(fake.createChannelArgsForCall)]
	fake.createChannelArgsForCall = append(fake.createChannelArgsForCall, struct {
		arg1 context.Context
		arg2 discord.ChannelName
	}{arg1, arg2})
	stub := fake.CreateChannelStub
	fakeReturns := fake.createChannelReturns
	fake.recordInvocation("CreateChannel", []interface{}{arg1, arg2})
	fake.createChannelMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ChannelCreator) CreateChannelCallCount() int {
	fake.createChannelMutex.RLock()
	defer fake.createChannelMutex.RUnlock()
	return len(fake.createChannelArgsForCall)
}

func (fake *ChannelCreator) CreateChannelCalls(stub func(context.Context, discord.ChannelName) (*pkg.Channel, error)) {
	fake.createChannelMutex.Lock()
	defer fake.createChannelMutex.Unlock()
	fake.CreateChannelStub = stub
}

func (fake *ChannelCreator) CreateChannelArgsForCall(i int) (context.Context, discord.ChannelName) {
	fake.createChannelMutex.RLock()
	defer fake.createChannelMutex.RUnlock()
	argsForCall := fake.createChannelArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ChannelCreator) CreateChannelReturns(result1 *pkg.Channel, result2 error) {
	fake.createChannelMutex.Lock()
	defer fake.createChannelMutex.Unlock()
	fake.CreateChannelStub = nil
	fake.createChannelReturns = struct {
		result1 *pkg.Channel
		result2 error
	}{result1, result2}
}

func (fake *ChannelCreator) CreateChannelReturnsOnCall(i int, result1 *pkg.Channel, result2 error) {
	fake.createChannelMutex.Lock()
	defer fake.createChannelMutex.Unlock()
	fake.CreateChannelStub = nil
	if fake.createChannelReturnsOnCall == nil {
		fake.createChannelReturnsOnCall = make(map[int]struct {
			result1 *pkg.Channel
			result2 error
		})
	}
	fake.createChannelReturnsOnCall[i] = struct {
		result1 *pkg.Channel
		result2 error
	}{result1, result2}
}

func (fake *ChannelCreator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ChannelCreator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.ChannelCreator = new(ChannelCreator)
