// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/notification-discord/pkg"
	"github.com/bborbe/notification/discord"
)

type ChannelIDFinder struct {
	FindByNameStub        func(context.Context, discord.ChannelName) (pkg.Channels, error)
	findByNameMutex       sync.RWMutex
	findByNameArgsForCall []struct {
		arg1 context.Context
		arg2 discord.ChannelName
	}
	findByNameReturns struct {
		result1 pkg.Channels
		result2 error
	}
	findByNameReturnsOnCall map[int]struct {
		result1 pkg.Channels
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ChannelIDFinder) FindByName(arg1 context.Context, arg2 discord.ChannelName) (pkg.Channels, error) {
	fake.findByNameMutex.Lock()
	ret, specificReturn := fake.findByNameReturnsOnCall[len(fake.findByNameArgsForCall)]
	fake.findByNameArgsForCall = append(fake.findByNameArgsForCall, struct {
		arg1 context.Context
		arg2 discord.ChannelName
	}{arg1, arg2})
	stub := fake.FindByNameStub
	fakeReturns := fake.findByNameReturns
	fake.recordInvocation("FindByName", []interface{}{arg1, arg2})
	fake.findByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ChannelIDFinder) FindByNameCallCount() int {
	fake.findByNameMutex.RLock()
	defer fake.findByNameMutex.RUnlock()
	return len(fake.findByNameArgsForCall)
}

func (fake *ChannelIDFinder) FindByNameCalls(stub func(context.Context, discord.ChannelName) (pkg.Channels, error)) {
	fake.findByNameMutex.Lock()
	defer fake.findByNameMutex.Unlock()
	fake.FindByNameStub = stub
}

func (fake *ChannelIDFinder) FindByNameArgsForCall(i int) (context.Context, discord.ChannelName) {
	fake.findByNameMutex.RLock()
	defer fake.findByNameMutex.RUnlock()
	argsForCall := fake.findByNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ChannelIDFinder) FindByNameReturns(result1 pkg.Channels, result2 error) {
	fake.findByNameMutex.Lock()
	defer fake.findByNameMutex.Unlock()
	fake.FindByNameStub = nil
	fake.findByNameReturns = struct {
		result1 pkg.Channels
		result2 error
	}{result1, result2}
}

func (fake *ChannelIDFinder) FindByNameReturnsOnCall(i int, result1 pkg.Channels, result2 error) {
	fake.findByNameMutex.Lock()
	defer fake.findByNameMutex.Unlock()
	fake.FindByNameStub = nil
	if fake.findByNameReturnsOnCall == nil {
		fake.findByNameReturnsOnCall = make(map[int]struct {
			result1 pkg.Channels
			result2 error
		})
	}
	fake.findByNameReturnsOnCall[i] = struct {
		result1 pkg.Channels
		result2 error
	}{result1, result2}
}

func (fake *ChannelIDFinder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ChannelIDFinder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.ChannelIDFinder = new(ChannelIDFinder)
